name: Build & Push to container registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        if: ${{ github.event_name == 'release' }}
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Extract flavor
        id: flavor
        run: if [ "${{ github.event_name }}" = "release" ]; then echo ::set-output name=name::; else echo ::set-output name=name::-dev; fi

      - name: Generate Docker image metadata
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        id: img_meta
        with:
          flavor: |
            latest=auto
            suffix=${{ steps.flavor.outputs.name }}
          images: ghcr.io/nezuchan/scheduled-tasks
          tags: |
            ${{ steps.tags.outputs.name }}
            latest
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: ./
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
