name: eslint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  eslint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
